### ISSUE TITLE
Unresolved type error in template.h excercise 8

### ISSUE THREAD

**Issue by tdnieder** [tghaefli/EBV#1]
error in:
void IpcSendImage(fract16 *f16Image, uint32 nPixels);
in template.h

fract16 indentifier is not recognised and produces an error

I'v tried #include <fract.h> which dind't solve the problem. Do you encounter the same problem?

**Comment by tghaefli** [comment]
You should only edit the file 'uebung08/app-template/process_frame.c' and nothing else. This error should not occur!

Did you use Zahns' app-template:
    git clone git://github.com/scs/oscar.git
    cd oscar
    git pull git://github.com/klaus-zahn/oscar.git master

Did you try in /app-template the command './configure' and set the correct path to oscar?

Did you try 'make clean', 'make deplay' ?
